### ISSUE TITLE
Too much data leads to presentation errors

### ISSUE THREAD

**Issue by hans1980775481** [ckRobinson/multi-column-markdown#35]
![image](https://user-images.githubusercontent.com/29484912/186804638-e3e8cbf4-2ee8-4af8-bc92-2a76e30ae46f.png)
![image](https://user-images.githubusercontent.com/29484912/186804690-4b6c2f56-5e88-4443-ba32-862ea72b4ea2.png)

**Comment by ckRobinson** [comment]
Hi there, I'm going to need more information in order to diagnose this issue. I have some files with very large column regions but do not see this issue on my end. Can you provide some raw markdown that is causing the issue? Using [pastebin.com](https://pastebin.com/) would be ideal and of course remove any private data from the file.
