### ISSUE TITLE
Support for having tables inside

### ISSUE THREAD

**Issue by dpeter99** [ckRobinson/multi-column-markdown#38]
I was trying to use this for having two smaller tables next to each other, but this seems to not work.

![image](https://user-images.githubusercontent.com/7725817/191064664-ca748281-5861-47d3-b383-194929ce75e6.png)

```
test:
`` `start-multi-column  
ID: ExampleRegion1  
number of columns: 2  
largest column: left  
`` `
r :
| A   | B   |
| --- | --- |
| a   | b   |
| a   | c   |
| b   | b   |

--- end-column ---

s: 
| A   | C   |
| --- | --- |
| a   | c   |
| b   | c   |

=== end-multi-column

```
(Added space in the ``start-multi-column`` tag to make GitHub show it nice)

**Comment by ckRobinson** [comment]
Hi there, this is actually a symptom of how Obsidian itself currently parses markdown. If you were to copy the table into an empty document without columns and switch to reading mode it would render the same way:

<img width="397" alt="Screen Shot 2022-09-29 at 3 24 30 PM" src="https://user-images.githubusercontent.com/70980846/193152946-3cf1c52d-0827-4490-92f5-9c4e919c3fc3.png">


Basically, because the "s:" is only one newline above the table, obsidian considers the entire block a paragraph and renders it as raw text.  The way to fix this is to add a blank line between the text and the table which then Obsidian will recognize one as raw text and the other as a table:

<img width="397" alt="Screen Shot 2022-09-29 at 3 24 39 PM" src="https://user-images.githubusercontent.com/70980846/193152956-feaa9b01-aebd-4b12-8628-249f3b771a7e.png">

<img width="252" alt="Screen Shot 2022-09-29 at 3 24 52 PM" src="https://user-images.githubusercontent.com/70980846/193152963-2f7eeabf-90f5-47d1-a81a-265488df253a.png">

<img width="384" alt="Screen Shot 2022-09-29 at 3 25 05 PM" src="https://user-images.githubusercontent.com/70980846/193152972-fee1a1d0-0a75-4f80-9f8f-ae3fac5d236e.png">

Native Obsidian Live Preview uses a different (more complicated, and AFAIA not available to plugins) method of parsing text and is able to recognize and render the table properly. Which is why this bug is not visible unless using the reading mode. I hope to provide some sort of fix for this at some point, because it is confusing, but am not sure when that will be.

**Comment by ckRobinson** [comment]
I have made a change to live preview in. 0.8.0 that fixes live preview rendering of tables. It does not change the requirement of a newline between the "table title" and the table data but tables should now render better within columns in live preview. Thanks.
