### ISSUE TITLE
Not working in reading view

### ISSUE THREAD

**Issue by carstenjaksch** [ckRobinson/multi-column-markdown#44]
Hi,

the columns do not show in reading mode.

Editing mode (syntax):
<img width="714" alt="Bildschirmfoto 2022-10-21 um 19 21 51" src="https://user-images.githubusercontent.com/82714642/197253326-5446fd9d-cc9b-4a4a-9d9d-ed7c3b09336b.png">

Editing mode (preview):
<img width="711" alt="Bildschirmfoto 2022-10-21 um 19 22 14" src="https://user-images.githubusercontent.com/82714642/197253393-34df2774-faa4-4e95-b034-3558cce8c64a.png">

Reading mode:
<img width="711" alt="Bildschirmfoto 2022-10-21 um 19 22 26" src="https://user-images.githubusercontent.com/82714642/197253437-47535ee3-1da7-4069-971b-9dd52450e8d4.png">

Obsidian and this plugin have the latest versions.

Additional plugins installed:
- Calendar
- Periodic Notes
- Reminder
- Smart Random Note
- Tasks
- Templater

Did I miss something?

**Comment by MatteCrystal** [comment]
I also just installed this plugin and am having the same issue.

**Comment by ckRobinson** [comment]
Hi there, there appears to be two issues here, one is that there is a typo in your screenshot. You have "columnn" typed with 2 "n"s which causes reading mode to not properly trigger the plugin, whereas live-preview uses a different method that isn't as syntactically strict.  

The other uncovered bug is that having multiple tabs of the same document open at the same time can cause render issues in reading mode. This bug has been fixed in an upcoming build but I am doing some additional testing and hope to release the patch over the weekend.

**Comment by ckRobinson** [comment]
The fix mentioned above has now been released so this should, hopefully, no longer be an issue. If you encounter the problem again feel free to let me know here or create a new issue!
