### ISSUE TITLE
Embed Note Link Trouble.

### ISSUE THREAD

**Issue by ham1204** [ckRobinson/multi-column-markdown#48]
Thanks for a very nice plugin.

I have the following problem when I include Embed Note Link in a column.

- The display appears and disappears.
- Other columns appear out of place
- Rebooting does not fix the problem.

And after that, even if I exclude Embed Note Link and replace it with normal text, the column continues to display abnormally.

It would be very helpful if the above could be resolved.

**Comment by ckRobinson** [comment]
Hi there, I think I know of the bug you are seeing but I'm not entirely sure. I did make a change to embeded notes in the new release (0.7.4) so if that solves the problem great! Otherwise if it is still occurring, could you provide some screenshots and some raw markdown so I can try and diagnose the issue?

**Comment by ckRobinson** [comment]
Closed due to inactivity.
