### ISSUE TITLE
Multi-Column Markdown stops Obsidian 1.1.0 from starting up

### ISSUE THREAD

**Issue by kithairon** [ckRobinson/multi-column-markdown#55]
[Bildschirmfoto.pdf](https://github.com/ckRobinson/multi-column-markdown/files/10157871/Bildschirmfoto.pdf)
macOS 12.6.1 |  MCM 0.7.4
Disabling the Plug-in solves the issue. Thanks for your work on a otherwise fine plugin!

**Comment by lishid** [comment]
The bug is caused by the use of `mdView.leaf` here: https://github.com/ckRobinson/multi-column-markdown/blob/89e3c8be3c09c12faf7add1d6b87996f477ee61c/src/live_preview/cm6_livePreview.ts#L257

This entire function can be replaced with a call to the `editorLivePreviewField`
https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L966

```ts
return state.field(editorLivePreviewField);
```

**Comment by BrianJChoi** [comment]
I am having the same problem, and it took me a few hours to see what plugin was causing the trouble, which I found was this one.

**Comment by ckRobinson** [comment]
Thanks @lishid for the advice, I’ll try and get something out to fix this issue tonight.

**Comment by kithairon** [comment]
Works fine here. Thanks for the quick update.

**Comment by chumido98** [comment]
after update, it did not render in editing mode
both plugin and obsidian is in newest version, please check

**Comment by ckRobinson** [comment]
Yup, that's what I get for rushing my test cases. Just released another build that fixes the backwards logic on editing mode/live preview rendering. Thanks for the heads up @chumido98.
