### ISSUE TITLE
high CPU usage

### ISSUE THREAD

**Issue by pcause** [ckRobinson/multi-column-markdown#6]
I was seeing very high CPU usage.  I figured it was a recent plugin addition.  I have the settings/community plugin opened and also task manager.  I went in and disabled recently added plugins.  When I disabled this plugin CPU dropped in almost half.  The page I had open is my homepage.  It is in reading mode and had NO multicolum markup

**Comment by ckRobinson** [comment]
I believe this is another symptom of one of the other known issues that I am currently working on. Is your homepage is a fairly large sized file?

Assuming it's the same root problem, I hope to get an update to fix this out soon.

**Comment by pcause** [comment]
no.  the home page has div across top with 3 iframes for weather, then 3 ```task queries (voerdue, today/tomorrow, next 10 days) , then 2 ```query for files in path.

**Comment by ckRobinson** [comment]
Hmm, well I'm not sure if that is a separate issue or not then. I just released a new update that *should* fix high CPU usage on pages without muti-column regions though so it may resolve itself. If you still see the problem after updating to the 0.4.0 release please feel free to let me know.

**Comment by pcause** [comment]
didn't fix for me. without enabled obsidian uses 4-5% CPU and with enabled 15+%

**Comment by ckRobinson** [comment]
I am not sure what the root cause of the problem is but will keep investigating.

**Comment by tiiins** [comment]
First of all, I want to say I love your plugin! That's exactly what I was looking for and I can create notes much better and more clearly with it.

I also noticed the problem with the high CPU, but now after the new update 0.4.0 it's gone.

However, there is another problem with the new update. This error message appears with the multicolums that have already been created:

```
Region ID is missing. Please set an id after the start tag.
EG: '=== multi-column-start: randomID'
Or use 'Fix Missing IDs' in the command palette and reload the document.
```

In principle, the fix is not a problem, as you can simply add a randomID, but it can be tedious to do this for every old multicolum.

**Comment by pcause** [comment]
Kind of agree.  If you find more than one multi-column use in a page and there are no IDs give the error.  If just one, should be fine.

**Comment by pcause** [comment]
Just tried 4.1 and seems to be fixed or at least a lot better.  CPU (i7-11xxx laptop) is still 6-10% and sometimes 10 just sitting there, no movement, not touching the app/window.  But definitely better.  I use sliding panes and when a second document opens there is a temporary spike but drops back to 6-10%.  What is strange is that if I have a non-column page displayed and the multi-column page is pinned but not displayed it still uses 6-10% whereas 2 non-multicolum pages uses 1% or less.

Not sure why after rendering the page and being in reading mode the CPU stays 6-10% but I guess I can live with that.  Perhaps some issue with the base obsidian?  I assume you only scan on page load/page change??

I guess sort of fixed and wish it was lower but not killing things any more.  THANKS

**Comment by ckRobinson** [comment]
> First of all, I want to say I love your plugin! That's exactly what I was looking for and I can create notes much better and more clearly with it.
> 
> I also noticed the problem with the high CPU, but now after the new update 0.4.0 it's gone.
> 
> However, there is another problem with the new update. This error message appears with the multicolums that have already been created:
> 
> ```
> Region ID is missing. Please set an id after the start tag.
> EG: '=== multi-column-start: randomID'
> Or use 'Fix Missing IDs' in the command palette and reload the document.
> ```
> 
> In principle, the fix is not a problem, as you can simply add a randomID, but it can be tedious to do this for every old multicolum.

Hey thanks, glad you like it. And yea, trust me I know it isn't ideal, I have a ton of files to go back through myself. That's why I added the "Fix Missing IDs' command to make the best of the situation. My new workflow is open a file, if I see the error message I just flip back to edit mode and run the command, swap to a new file and back and everything is fine. It's kind of a hassle but eventually I won't have to do it any more.

Also I did just release 0.4.2 which allows for a single empty region per document so hopefully that helps both of you out.

> Just tried 4.1 and seems to be fixed or at least a lot better. CPU (i7-11xxx laptop) is still 6-10% and sometimes 10 just sitting there, no movement, not touching the app/window. But definitely better. I use sliding panes and when a second document opens there is a temporary spike but drops back to 6-10%. What is strange is that if I have a non-column page displayed and the multi-column page is pinned but not displayed it still uses 6-10% whereas 2 non-multicolum pages uses 1% or less.

I'm still sort of at a loss about this. I don't really see obsidian holding a high percentage of the cpu on both of my test machines (1 mac, 1 windows). I'm wondering if it is some kind of conflict with another plugin you have installed that is causing the document to be constantly re-rendered. I checked with sliding-panes and thought I saw the issue but after a minute or so everything went back to normal. 

> Not sure why after rendering the page and being in reading mode the CPU stays 6-10% but I guess I can live with that. Perhaps some issue with the base obsidian? I assume you only scan on page load/page change??

Yea the only time the plugin should do anything is on load or if you modify the document. The first render of a file will cause a CPU spike but it should drop pretty quick. And unless there is something causing the document to be reloaded multiple times a second I am not sure why it would be holding 5-10% of the CPU. I'm working on another update that might reduce CPU usage again but it's still early in the process so it may not work out the way I hope. Since I can't really replicate the issue I'm sort of working blind to fix what I view as potential problems but I'll see what else I can do.

**Comment by pcause** [comment]
think i figured it out.  as I said above in the right colum I have 2 task queries (```task ) and then 2 filepath queries:

```query
path:some/path/
```

when i move the 2 such queries out of the right side of the table to after the table the CPU usage problem goes basically away!  Must be that the file queries are always updating the page and so you are always rescanning.

**Comment by ckRobinson** [comment]
That could be it! I'll see if I can replicate it.

**Comment by ckRobinson** [comment]
Yup, that's the issue, holding my CPU at 12%. Not sure what I can do to fix it at this point but at least now the bug is identified.

**Comment by pcause** [comment]
you might post to the app devs on discord or the community site.  think discord is likely the right place.  put at least we know

**Comment by Gnopps** [comment]
I'm facing the same issue (I guess it is). If I put the [Obsidian tasks](https://github.com/schemar/obsidian-tasks) inside a column then the page seems to reload frequently (shown in the developer console that the page keeps updating) even though I do nothing to the tasks.
