### ISSUE TITLE
[Feature request] Using Custom Frames with Mutli-Column Markdown

### ISSUE THREAD

**Issue by jch-en** [ckRobinson/multi-column-markdown#65]
I've been using MCM with the [Custom Frames](https://github.com/Ellpeck/ObsidianCustomFrames) plugin to put iframes side-by-side. When opening a page, the iframes load once but need to be clicked on to be interacted with, which loads them again. It would be better if the iframes load once when the page is loaded and stay like that while you're on the page.

**Comment by tyePhDCandy** [comment]
> I've been using MCM with the [Custom Frames](https://github.com/Ellpeck/ObsidianCustomFrames) plugin to put iframes side-by-side. When opening a page, the iframes load once but need to be clicked on to be interacted with, which loads them again. It would be better if the iframes load once when the page is loaded and stay like that while you're on the page.

same here. have you solved the problem? or did you find another good multi column plugin?

**Comment by ckRobinson** [comment]
Hi, the core problem of this bug is due to how Obsidian handle mouse interactions causing the document to re-render before the frame is interactable. As far as I can tell right now, not fixable. I have however added a fix in 0.8.0 that should fix cross compatibility with Custom Frames so they render properly in Reading mode.
