### ISSUE TITLE
[Bug] Rendering code block inside a column 

### ISSUE THREAD

**Issue by Hchour** [ckRobinson/multi-column-markdown#66]
First I would like to thank you for this great work. It is really a nice plugin.

I tried adding a block code in the column. it was added successfully but the copy bottom always appear and it does not work as you can see in the attached fig.
Beside it would be nice if we have the option between a wrap column and non-wrap column so if we have a wide horizontal content in a column a scroll bar can be used instead of wrapping the contents.

![image](https://user-images.githubusercontent.com/123549712/214539726-cef5606b-7b49-439a-ab92-3cde17151aba.png)

Thanks in advance,
Best regards,

**Comment by ckRobinson** [comment]
Hi there, it is a know issue in live preview that any interactable buttons within columns do not work, and this appears to be another case. I am not sure if this will ever be fixed due to how Obsidian handles the mouse clicks but I will keep exploring options when I have the time.

As far as separate column wrap options per column, this has been added in 0.8.0, you can use the new array syntax to define each column's overflow state, see the Region Settings portion of the readme for more info.
