### ISSUE TITLE
Need more doc

### ISSUE THREAD

**Issue by Larry-Louis** [ckRobinson/multi-column-markdown#80]
How to make Region Settings work? Can someone give a 2 col with 30% width and 70% width code example?

**Comment by ckRobinson** [comment]
> \```start-multi-column\
> Number of Columns: 2\
> Column Size: [30%, 70%]\
> \```

Although the way percentages are calculated is off of the total editor width. So because there is a bit of spacing between columns by default I would recommend reducing the percentages, or setting column spacing to zero:
 
> \```start-multi-column\
> Number of Columns: 2\
> Column Size: [30%, 70%]\
> Column Spacing: 0px\
> \```

Otherwise the columns would be pushed beyond the editor width, and include a horizontal scrollbar.

I have also added an additional example to the full examples page [here](https://github.com/ckRobinson/multi-column-markdown/blob/0.8.1/documentation/FullExamples.md), and added additional syntax examples in the ReadMe.

**Comment by Larry-Louis** [comment]
Thanks for reply. I just need it.

**Comment by Larry-Louis** [comment]
> > ```start-multi-column
> > Number of Columns: 2
> > Column Size: [30%, 70%]
> > ```
> 
> Although the way percentages are calculated is off of the total editor width. So because there is a bit of spacing between columns by default I would recommend reducing the percentages, or setting column spacing to zero:
> 
> > ```start-multi-column
> > Number of Columns: 2
> > Column Size: [30%, 70%]
> > Column Spacing: 0px
> > ```
> 
> Otherwise the columns would be pushed beyond the editor width, and include a horizontal scrollbar.
> 
> I have also added an additional example to the full examples page [here](https://github.com/ckRobinson/multi-column-markdown/blob/0.8.1/documentation/FullExamples.md), and added additional syntax examples in the ReadMe.

Thanks for reply. I just need it.
