### ISSUE TITLE
Collapsing / Expanding Callouts

### ISSUE THREAD

**Issue by tsteckenborn** [ckRobinson/multi-column-markdown#81]
Anybody else has issues with collapsing / expanding callouts?

The callout itself seems to be rendered, but the expand and collapse doesn't seem to be working within a multi-column.

**Comment by ckRobinson** [comment]
Hi there, if you are talking about callouts within Live Preview mode then yes, that is a known issue. In fact any button interaction within a Live Preview multi-column region will not work properly due to how Live Preview is implemented. 

Callouts do properly expand and collapse, and most other buttons do activate, when using Reading mode however.

**Comment by tsteckenborn** [comment]
I'm experiencing it within reading mode. Will have a more detailed look tomorrow.

**Comment by VaultVulp** [comment]
Just started using this plung and I'm having the same issue.
 @tsteckenborn were you able to resolve this problem?

**Comment by tsteckenborn** [comment]
No, ended up utilizing another plugin.

**Comment by VaultVulp** [comment]
Thanks! Have a good one!

**Comment by ckRobinson** [comment]
Hi all, sorry for the super long response time, but I have made changes in version 0.9.0 that should resolve this issue. Thanks.
