### ISSUE TITLE
Backlinks do not render

### ISSUE THREAD

**Issue by RedLilith** [ckRobinson/multi-column-markdown#83]
when adding backlinks inside of text in multi-column, the link does not show and is not clickable.

Source mode:
<img width="615" alt="image" src="https://github.com/ckRobinson/multi-column-markdown/assets/134121219/1a6f8693-f8f1-4d31-bfc5-5d1529242fb6">

Rendered:
<img width="674" alt="image" src="https://github.com/ckRobinson/multi-column-markdown/assets/134121219/c84c6c4e-3d61-4230-9a30-ece96dc90145">

expected behavior (using a different column plugin to make it work):
<img width="653" alt="image" src="https://github.com/ckRobinson/multi-column-markdown/assets/134121219/d2a3611a-64e3-411c-b325-4d5022322ce1">

**Comment by ckRobinson** [comment]
Hi there, the problem seems to be that your column break flag is appended to the end of the paragraph above it:

> This is Happy Bakers information take from the [[wages and tax statements, form w-2|W-2]] shown [[Payroll Reporting|here]]. Although his (etc...)
> --- column-end ---

In the past, this situation would cause the column-break to be ignored. But a recent update allows them to be recognized as column break tags but seems to have broken the links within the paragraph itself. Easy solution for now, just add an additional line between the column break: 

> This is Happy Bakers information take from the [[wages and tax statements, form w-2|W-2]] shown [[Payroll Reporting|here]]. Although his (etc...)
>
> --- column-end ---

And that will render the links properly. I will see what I can do to fix the root issue.

**Comment by ckRobinson** [comment]
Hi, I have not been able to directly fix this issue but have released version 0.9.0 that now attempts to detect when this issue occurs and adds a warning message informing the you about how to fix the syntax. If you see any other issues feel free to let me know and I will take a look when I can, thanks.
